export class Consumidor {
	idConsumidor: number;
	nacionalidad: number;
	tipoDocumento: number;
	tipoConsumidor: string;
	documentoIdentificacion: string;
	pais: number;
	representanteLegal: string;
	nitConsumidor: string;
	nombreEmpresa: string;
	razonSocial: string;
	nombre1: string;
	nombre2: string;
	nombre3: string;
	apellido1: string;
	apellido2: string;
	apellidoCasada: string;
	genero: string;
	etnia: number;
	motivoQueja: number;
	idMotivoQueja : number
	codigoMunicipio: number;
	codigoDepartamento: number;
	direccionCalle: string;
	direccionAvenida: string;
	direccionZona: string;
	direccionDetalle: string;
	sedeDiacoCercana: number;
	telefonoCelular: string;
	telefonoDomicilio: string;
	telefonoReferencia: string;
	email: string;
	email2: string;
	iCheck: string;
	autorizoPublicar : string;
	habilitadoNotificacionElectronica: string;
	fechaAdicion: Date;
	usuarioAdiciono: string;
	usuarioModifico: string;
	emailConfirmation:string;
	email2Confirmation:string;
	idPais: number;
	idEtnia: number;
	telefono: string;
	domicilio: string;
	referencia: string;
	correoElectronico1: string;
	correoElectronico2: string;
}
