export class Proveedor {
  idProveedor: number;
	nombre: string;
	nitProveedor: string;
	direccion: string;
	habilitadoConciliacionPrevia: string;
	codigoDepartamento: number;
	habilitadoNotificacionElectronica: string;
	habilitado: string;
	codigoMunicipio: number;
	fechaRegistroConciliacionPrevia: Date;
	fechaAdicion: Date;
	fechaModificacion: Date;
	usuarioAdiciono: string;
	usuarioModifico: string;
  primerNombre: string;
	segundoNombre: string;
	tercerNombre: string;
	primerApellido: string;
	segundoApellido: string;
	apellidoCasada: string;
	nombreEmpresa: string;
	razonSocial: string;
	direccionCalle: string;
	direccionAvenida: string;
	direccionZona: string;
	direccionDetalle: string;
  idActividadEconomica: number;
	idTipoComercio: number;
	telefono: string;
	email: string;
  tipoProveedor: number;
  email1 : string;
  email2 : string;
  telefono1 : string;
  telefono2 : string;
  telefono3 : string;
}
