export class Quejaini {
  idQueja: number;
	idConsumidor: number;
	idProveedor: number;
	idEstadoQueja: number;
	idSubActividadEconomica: number;
	facturaNumero: string;
	fechaFactura: Date;
	fechaFactura_: string;
	detalleQueja: string;
	solicitaQue: string;
	procedeQueja: string;
	razonNoProcede: string;
	datosVerificados: string;
	fechaQueja: Date;
	motivo: string;
	idDepartamento: number;
	idMunicipio: number;
	usuarioAsignado: number;
	idDiacoSede: number;
	anio: number;
	noQueja: number;
	nombre: string;
	dpiPasaporte: string;
	telefono: string;
	correo: string;
	nitProveedor: string;
	apellido: string;
	ubicacion: string;
	secuencia: number;
	idFuente: string;
	presencial: string;
	pregunta : string;
	carchivos : string;
	cdatos : string;
	respuesta : string;
	docp : string;
    docc : string;
    nomp : string;
    nomc : string;
}
