export class Queja {
	idQueja: number;
	idConsumidor: number;
	idProveedor: number;
	idEstadoQueja: number;
	idSubActividadEconomica: number;
	facturaNumero: string;
	fechaFactura: Date;
	fechaFactura_: string;
	detalleQueja: string;
	solicitaQue: string;
	procedeQueja: string;
	razonNoProcede: string;
	datosVerificados: string;
	fechaQueja: Date;
	motivo: string;
	idDepartamento: number;
	idMunicipio: number;
	usuarioAsignado: number;
	idDiacoSede: number;
	anio: number;
	noQueja: number;
	fuente: string;
	idfuente: number;
	ubicacion: string;
	documentado: string;
	expiradomail: number;
	flagalerta: number;
	direccionProveedor: string;
	idDepartamentoProveedor: number;
	idMunicipioProveedor: number;
	idEstablecimiento : number;
	zonaProveedor : string;
	pregunta : string;
	carchivos : string;
	cdatos : string;
	respuesta : string;
	docp : string;
    docc : string;
    nomp : string;
    nomc : string;	
}